Implement shop 1
blue-lupi/blue-lupi-homepage pull request #35
Opened 2019-11-14 08:18 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, there is no shop implemented. #31 
- Currently, the footer does not fit the theme. #27 
- Currently, the website has countless little fields of interest which require improvement.

**What is the new behavior (if this is a feature change)?**
- The shop has been implemented. #31 
- The footer has been improved. #27 
- The Sub and Blackwolf components have been updated.
- The FAQ has been updated.
- The navigation icon is now the button to launch the shop cart.
- Types in the dummy data have been fixed.
- The code quality has been improved by enforcing our guidelines.

**Other information**:
- The version has been updated to v0.3.0
[Learn more about our versioning](https://github.com/aichner/React-MDB-Template#versioning)

2019-11-14 08:23 UTC, Aichnerc reviewed
Looks good to me.

2019-11-26 22:14 UTC, schettn requested changes
Should be ok to merge after one change.

2019-11-26 22:14 UTC, schettn commented on src/components/molecules/Cart/index.jsx
> +  super(props);
The indents do not look right. Please correct them.

2019-11-26 22:19 UTC, schettn approved these changes
Should be ok to merge.

2019-11-26 22:55 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2019-11-26 22:55 UTC, kleberbaum commented on src/components/molecules/Cart/index.jsx
> +  super(props);
There should be some kind of indentation.

2019-11-26 22:55 UTC, kleberbaum commented on src/components/organisms/Sections/Shop/index.jsx
> +
Please strip all unnecessary newline.

2019-11-26 22:55 UTC, kleberbaum commented on src/components/organisms/Sections/BlackWolf/index.jsx
> +
Please strip all unnecessary newline.

2019-11-26 22:55 UTC, kleberbaum commented on src/utilities/checkout.js
> + */
Please end every source file with a newline.

2019-11-26 23:08 UTC, kleberbaum approved these changes
Should be ok to merge.

2019-11-26 23:08 UTC, merged