Improve page 1
blue-lupi/blue-lupi-homepage pull request #38
Opened 2020-04-17 14:09 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, there is a problem with the token authentication, that causes the page to refresh every 4 minutes. The problem has been identified as wrong token auth, refresh token handling and calling a function every 4 minutes to relogin.
- Currently, it takes ages for the page to load. (1200ms locally)
- Currently, the design of the Carts is not responsive and buggy, while also not including a proper checkbox for e-commerce law.
- Currently, there can only be one shop.
- Currently, the Blue Lupi logo is always on top (also at the black wolf sections).
- Currently, the personalized section is broken. There is no product to purchase.
- Currently, there is no ´MessagePage´ to display pages like about, privacy, ...
- Currently, the ScrollToTop fix has not been added.
- Currently, there is no Progress Bar in the Cart to show how much is remaining until free shipping.
- Currently, the FAQ are displayed statically.
- Currently, the repository does not follow our coding guidelines.
- Currently, the page is not fit for static use.

**What is the new behavior (if this is a feature change)?**
- The token auth has been fixed. The page does not longer auto-refresh.
- The loading speed has been greatly improved by rendering the ´Hero´ component on page load and fill in details like the picture and button with animations after the data has been fetched. The page load time is now 500ms (locally).
- The Cart has been reworked and is now fully functional.
- A second shop section can be added to display Black Wolf products. This has been done by looking at Shopify collection values and displaying them accordingly, infused with using the title in the CMS to define the collection name of the black wolf product collection.
- The Blue Lupi logo is no longer visible on black wolf sections.
- The personalized section has been fixed. The collection has been used instead of the product name to be more flexible with naming the product while keeping the functionality.
- A ´MessagePage´ has been added to display all kinds of pages like about, privacy, ...
- The ScrollToTop fix has been added. This always displays the page on its top when changing pages.
- The Progress Bar for free shipping has been added to the Cart.
- The FAQ are now being shown when clicking on the title.
- The code quality has been improved by enforcing our coding guidelines based on ES6.
- The static page fix has been applied and the page is now ready for static use.

2020-04-17 14:35 UTC, pinterid commented on src/Routes.js
> +          path="/widerruf"
Path name could be changed to "cancellation", to be in the same language as the other pathnames.

2020-04-17 14:47 UTC, pinterid commented on src/components/molecules/Cart/cart.scss
>  }
Missing new line.

2020-04-17 14:48 UTC, pinterid commented on src/components/molecules/Cart/index.jsx
>      this.openCheckout = this.openCheckout.bind(this);
Missing new line.

2020-04-17 19:11 UTC, schettn requested changes
Should be ok to merge after few changes.

2020-04-17 19:11 UTC, schettn commented on public/404.html
> +
Remove this newline

2020-04-17 19:11 UTC, schettn commented on public/404.html
> +      var l = window.location;
Add a new line

2020-04-17 19:11 UTC, schettn commented on public/index.html
> +          var q = {};
Add newline

2020-04-17 19:11 UTC, schettn commented on public/index.html
> +              var a = v.split("=");
Add newline

2020-04-17 19:11 UTC, schettn commented on src/App.js
>      let currentTS = ~~(Date.now() / 1000);
Add newline

2020-04-17 19:11 UTC, schettn commented on src/index.js
>  });
Add new line

2020-04-17 19:11 UTC, schettn commented on src/index.js
>  }));
Add new line

2020-04-17 19:11 UTC, schettn commented on src/components/pages/MessagePage/index.jsx
> +    const data = globalState ? globalState.page : null;
Add new line

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +        );
Add new line

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +        sections.push(cart);
Add new line

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +      : undefined;
Add new line

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
Remove this line

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +    );
Add a newline

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +      if (page && form && !this.props.loading && this.props.data.shop) {
Add newline

2020-04-17 19:11 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +    if (this.props.globalState) {
Add newline

2020-04-17 19:11 UTC, schettn commented on src/components/helpers/InstagramFeed.jsx
> +          );
Add newline

2020-04-17 19:11 UTC, schettn commented on src/components/helpers/InstagramFeed.jsx
> +          return {
Add newline

2020-04-17 19:11 UTC, schettn commented on src/components/molecules/Cart/index.jsx
>      super(props);
Add a newline after the super call

2020-04-17 19:11 UTC, schettn commented on src/components/molecules/Product/index.jsx
>      let initialVariant = this.props.product.node.variants.edges[0].node.id;
add a newline

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Hero/index.jsx
> +    if(data.slideImage){
Missing indents. Change to: 
if (data.slideImage) {}

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Sections/BlackWolf/index.jsx
>        let res = {};
add a newline

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Sections/FAQ/index.jsx
> +  state = {};
add a newline

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Sections/Features/index.jsx
>      });
add a newline

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Sections/Steps/index.jsx
> +                  if (error) return null;
add newline

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Sections/Steps/index.jsx
> +                  if (error) return null;
add newline

2020-04-17 19:11 UTC, schettn commented on src/components/organisms/Sections/Trust/index.jsx
> +                      if (error) return null;
add newline

2020-04-17 21:13 UTC, schettn approved these changes
LGTM!

2020-04-18 06:23 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-04-18 06:23 UTC, kleberbaum commented on public/404.html
> +
no newline

2020-04-18 06:23 UTC, kleberbaum commented on src/components/atoms/LineItem/index.jsx
> +                    -
whitespace?

2020-04-18 06:23 UTC, kleberbaum commented on src/components/atoms/LineItem/index.jsx
> +                    +
whitespace?

2020-04-18 06:23 UTC, kleberbaum commented on src/components/helpers/InstagramFeed.jsx
> +        `https://www.instagram.com/graphql/query?query_id=17888483320059182&variables={"id":"${this.props.userId}","first":${this.props.photoCount},"after":null}`
120c

2020-04-18 06:23 UTC, kleberbaum commented on src/components/helpers/InstagramFeed.jsx
> +          const url = `https://www.instagram.com/p/${node.shortcode}`;
newline

2020-04-18 06:23 UTC, kleberbaum commented on src/components/molecules/Cart/index.jsx
> +
Please remove newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/molecules/Cart/index.jsx
> +              Ich akzeptiere die{" "}
space

2020-04-18 06:23 UTC, kleberbaum commented on public/404.html
> +      var l = window.location;
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/helpers/InstagramFeed.jsx
> +	state = { photos: [] };
It would be best to introduce 2 space indentation to this file.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/molecules/Cart/cart.scss
> +	.totals {
It would be best to introduce 2 space indentation to this file.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/molecules/Cart/index.jsx
> +	MDBModal,
It would be best to introduce 2 space indentation to this file.
Why have you even switched back to 4 space indent?

2020-04-18 06:23 UTC, kleberbaum commented on src/components/molecules/Product/index.jsx
>      let initialVariant = this.props.product.node.variants.edges[0].node.id;
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Hero/hero.scss
> +
Please remove newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Hero/index.jsx
> +	MDBView,
It would be best to introduce 2 space indentation to this file.
Why have you even switched back to 4 space indent?

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Sections/About/index.jsx
>      let rtn = cards.map((card, i) => {
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Sections/About/index.jsx
>      let rtn = cards.map((card, i) => {
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Sections/Shop/index.jsx
Please remove this newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Sections/Shop/index.jsx
> -
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/organisms/Sections/Steps/index.jsx
> +                  if (error) return null;
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/components/pages/HomePage/index.jsx
> +      const form = this.props.globalState.form;
Please add a newline.

2020-04-18 06:23 UTC, kleberbaum commented on src/utilities/_base.scss
>  }
Please add a newline.

2020-04-18 07:01 UTC, pinterid requested changes
Should be good to merge after a few changes.

2020-04-18 07:03 UTC, pinterid approved these changes
Can be merged.

2020-04-18 08:45 UTC, Aichnerc commented on src/components/atoms/LineItem/index.jsx
> +                    -
No, just properly formatted.

2020-04-18 08:45 UTC, Aichnerc commented on src/components/atoms/LineItem/index.jsx
> +                    +
No, just properly formatted.

2020-04-18 09:08 UTC, Aichnerc commented on src/components/helpers/InstagramFeed.jsx
> +	state = { photos: [] };
This appears to be a bug. The indentation is actually set to 2 spaces.

2020-04-18 09:09 UTC, Aichnerc commented on src/components/molecules/Cart/cart.scss
> +	.totals {
This appears to be a bug. The indentation is actually set to 2 spaces.

2020-04-18 09:09 UTC, Aichnerc commented on src/components/molecules/Cart/index.jsx
> +	MDBModal,
This appears to be a bug. The indentation is actually set to 2 spaces.

2020-04-18 09:10 UTC, Aichnerc commented on src/components/organisms/Hero/index.jsx
> +	MDBView,
This appears to be a bug. The indentation is actually set to 2 spaces.

2020-04-18 14:02 UTC, Aichnerc commented on src/index.js
>  });
Not approving, once this is part of a main heading.

2020-04-18 17:38 UTC, Aichnerc commented on src/index.js
>  }));
Not approving, once this is part of a main heading.

2020-04-18 19:46 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-04-18 19:46 UTC, kleberbaum commented on src/components/organisms/Hero/hero.scss
> +  }
Please add a newline.

2020-04-18 19:46 UTC, kleberbaum commented on src/components/organisms/Sections/About/index.jsx
Please remove this newline.

2020-04-18 19:46 UTC, kleberbaum commented on src/components/organisms/Sections/About/index.jsx
Please remove this line.

2020-04-19 08:18 UTC, Aichnerc commented on src/components/organisms/Hero/hero.scss
> +  }
Nope, common header.

2020-04-19 09:27 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-04-19 09:28 UTC, merged